### ISSUE TITLE
Error on Opening Relic Draw

### ISSUE THREAD

**Issue by mjpalestina** [rk-squared/rk-squared#1]
Error:
Opening Relic Draw created the following Error.
Windows: 10x64 v1809
Android: v8.0.0

RangeError: Maximum call stack size exceededRangeError: Maximum call stack size exceeded
    at Array.sort (native)
    at file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195751
    at e.exports (file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195899)
    at file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195849
    at e.exports (file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195899)
    at file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195849
    at e.exports (file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195899)
    at file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195849
    at e.exports (file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195899)
    at file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195849

**Comment by BrewersFanJP** [comment]
I believe the following issue is related, when opening the Record Materia screen after following the instructions:

RangeError: Maximum call stack size exceededRangeError: Maximum call stack size exceeded
    at Array.sort (native)
    at file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195751
    at e.exports (file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195899)
    at file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195849
    at e.exports (file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195899)
    at file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195849
    at e.exports (file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195899)
    at file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195849
    at e.exports (file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195899)
    at file:///C:/Users/username/AppData/Local/Programs/rk-squared/resources/app.asar/app/dist/renderer.prod.js:900:195849

**Comment by joshkel** [comment]
Thanks for the bug reports. Sorry for the delay reply.

It looks like these error messages are pretty deep within some third-party code, so I'm having trouble tracking them down. I'll keep looking, though.

I'm guessing that RK Squared's saved state got corrupted somehow. If you are still having problems, or if the error comes back, could you please send your config.json to me? You can find the path to config.json under RK Squared's Options screen.

**Comment by joshkel** [comment]
I found and fixed the bug. The fix will be in the next release, due within the next day or two.
